import { promises as fs } from "node:fs";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const project = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repository = path.dirname(project);
const require = createRequire(path.join(project, "desktop/package.json"));
const manifest = JSON.parse(await fs.readFile(path.join(project, "tools/icon-sources.json"), "utf8"));
const check = process.argv.includes("--check");
if (process.argv.slice(2).some(value => value !== "--check")) throw new Error("Usage: generate-icons.mjs [--check]");

function packageDirectory(name, version) {
  const filename = require.resolve(`${name}/package.json`);
  if (require(filename).version !== version) throw new Error(`Install the pinned ${name}@${version} with npm ci in truedown/desktop`);
  return path.dirname(filename);
}

const source = packageDirectory(manifest.package, manifest.version);
packageDirectory(manifest.renderer, manifest.rendererVersion);
const { Resvg } = require(manifest.renderer);
const license = (await fs.readFile(path.join(source, "LICENSE"), "utf8")).trim();
const provenance = `${manifest.package} ${manifest.version}; https://lucide.dev; generated by truedown/tools/generate-icons.mjs`;
const header = `<!-- ${provenance}\n\n${license.replace(/^---$/gm, "")}\n-->`;
const bodies = new Map();
function addIcon(id, svg) {
  if (!/^[a-z][a-z0-9-]*$/.test(id) || bodies.has(id)) throw new Error("Invalid or duplicate icon identifier");
  const match = svg.replace(/<!--[^]*?-->/g, "").trim().match(/^<svg\b[^>]*>([^]*?)<\/svg>$/);
  if (!match || !/viewBox="0 0 24 24"/.test(svg)) throw new Error(`Unexpected icon source: ${id}`);
  const body = match[1].trim().replace(/\s*\n\s*/g, "");
  if (/<\/?(?!path\b|circle\b|ellipse\b|rect\b|line\b|polyline\b|polygon\b)/.test(body)) throw new Error(`Icon requires unsupported elements: ${id}`);
  bodies.set(id, body);
}
for (const [id, upstream] of Object.entries(manifest.icons)) {
  if (!/^[a-z][a-z0-9-]*$/.test(upstream)) throw new Error("Invalid icon source");
  addIcon(id, await fs.readFile(path.join(source, "icons", `${upstream}.svg`), "utf8"));
}
for (const id of manifest.projectIcons) {
  if (!/^[a-z][a-z0-9-]*$/.test(id)) throw new Error("Invalid project icon source");
  addIcon(id, await fs.readFile(path.join(project, "tools/icons", `${id}.svg`), "utf8"));
}

let outputs = 0;
async function output(relative, data) {
  const filename = path.resolve(repository, relative);
  if (!filename.startsWith(repository + path.sep)) throw new Error("Icon output escaped the repository");
  let directory = repository;
  for (const part of path.relative(repository, path.dirname(filename)).split(path.sep)) {
    directory = path.join(directory, part);
    try {
      const stat = await fs.lstat(directory);
      if (!stat.isDirectory() || stat.isSymbolicLink()) throw new Error(`Unsafe icon directory: ${directory}`);
    } catch (error) {
      if (error.code !== "ENOENT" || check) throw error;
      await fs.mkdir(directory);
    }
  }
  let current;
  try {
    const stat = await fs.lstat(filename);
    if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Unsafe icon output: ${relative}`);
    current = await fs.readFile(filename);
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
  }
  const binary = Buffer.isBuffer(data);
  const expected = binary ? data : Buffer.from(data.replace(/\r\n/g, "\n"));
  const matches = binary ? current?.equals(expected) : current?.toString("utf8").replace(/\r\n/g, "\n") === expected.toString("utf8");
  if (!matches) {
    if (check) throw new Error(`Generated icon asset is stale: ${relative}. Run npm run icons:sync in truedown/desktop.`);
    await fs.writeFile(filename, expected);
  }
  outputs += 1;
}

function sprite(ids) {
  const symbols = ids.map(id => {
    if (!bodies.has(id)) throw new Error(`Unknown icon: ${id}`);
    const credit = manifest.projectIcons.includes(id) ? `  <!-- Project-drawn ${id} provider mark. -->\n` : "";
    return `${credit}  <symbol id="icon-${id}" viewBox="0 0 24 24">${bodies.get(id)}</symbol>`;
  });
  return `${header}\n<svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true">\n${symbols.join("\n")}\n</svg>\n`;
}

await output("shared/icons.svg", sprite(manifest.extension));
await output("truedown/web/icons.svg", sprite([...bodies.keys()]));

function render(svg, size) {
  // Rasterize the vector at its final physical size; never enlarge a small
  // frame or blur it by shrinking an intermediate screenshot.
  return new Resvg(svg, { fitTo: { mode: "width", value: size }, font: { loadSystemFonts: false } }).render().asPng();
}

for (const id of manifest.nativeMenu) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#808080" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${bodies.get(id)}</svg>`;
  for (const size of [16, 32]) await output(`truedown/desktop/icons/menu/${id}-${size}.png`, render(svg, size));
}

const brand = await fs.readFile(path.join(project, "web/truedown-logo.svg"));
const frames = new Map();
function brandFrame(size) {
  if (!frames.has(size)) frames.set(size, render(brand, size));
  return frames.get(size);
}

// Tauri's ICO loader decodes the first entry for its default window icon.
// Keep the largest vector raster first so taskbar icons are never enlarged.
const windowsSizes = [...manifest.windowsSizes].sort((left, right) => right - left);
const iconDirectory = Buffer.alloc(6 + windowsSizes.length * 16);
iconDirectory.writeUInt16LE(1, 2);
iconDirectory.writeUInt16LE(windowsSizes.length, 4);
let offset = iconDirectory.length;
const windowsFrames = windowsSizes.map((size, index) => {
  const frame = brandFrame(size);
  const entry = 6 + index * 16;
  iconDirectory[entry] = iconDirectory[entry + 1] = size === 256 ? 0 : size;
  iconDirectory.writeUInt16LE(1, entry + 4);
  iconDirectory.writeUInt16LE(32, entry + 6);
  iconDirectory.writeUInt32LE(frame.length, entry + 8);
  iconDirectory.writeUInt32LE(offset, entry + 12);
  offset += frame.length;
  return frame;
});
await output("truedown/windows/truedown.ico", Buffer.concat([iconDirectory, ...windowsFrames]));

const macChunks = Object.entries(manifest.macRepresentations).map(([type, size]) => {
  const frame = brandFrame(size);
  const header = Buffer.alloc(8);
  header.write(type, 0, "ascii");
  header.writeUInt32BE(8 + frame.length, 4);
  return Buffer.concat([header, frame]);
});
const macHeader = Buffer.alloc(8);
macHeader.write("icns", 0, "ascii");
macHeader.writeUInt32BE(8 + macChunks.reduce((sum, chunk) => sum + chunk.length, 0), 4);
await output("truedown/macos/truedown.icns", Buffer.concat([macHeader, ...macChunks]));

const noticePath = path.join(project, "THIRD_PARTY_NOTICES.md");
const notice = await fs.readFile(noticePath, "utf8");
const start = "<!-- BEGIN GENERATED LUCIDE NOTICE -->";
const end = "<!-- END GENERATED LUCIDE NOTICE -->";
const section = `${start}\n## Lucide icons\n\nTrueDown uses selected icons from [Lucide](https://lucide.dev), pinned to\n\`${manifest.package}@${manifest.version}\`. The dashboard, native controls and\ntray menu share these source shapes. The original TrueDown logo remains\nproject artwork. Icons are generated at build time; no icon JavaScript library\nor network request runs in the application.\n\n${license}\n${end}`;
const existing = new RegExp(`${start}[^]*?${end}`);
const updated = existing.test(notice) ? notice.replace(existing, section) : `${notice.trimEnd()}\n\n${section}\n`;
await output("truedown/THIRD_PARTY_NOTICES.md", updated);
console.log(`${check ? "Verified" : "Generated"} ${outputs} icon assets and notices from ${manifest.package}@${manifest.version}`);
